[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
  me-no-dev/AsyncTCP @ ^1.1.1
  zeed/ESP Async WebServer @ 1.2.3
  bblanchon/ArduinoJson @ ^7.1.0
