#pragma once

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define CAMERA_HOSTNAME "esp32-cam"

#define CAMERA_USE_STATIC_IP true
#define CAMERA_STATIC_IP_1 172
#define CAMERA_STATIC_IP_2 20
#define CAMERA_STATIC_IP_3 10
#define CAMERA_STATIC_IP_4 11
#define CAMERA_GATEWAY_1 172
#define CAMERA_GATEWAY_2 20
#define CAMERA_GATEWAY_3 10
#define CAMERA_GATEWAY_4 1
#define CAMERA_SUBNET_1 255
#define CAMERA_SUBNET_2 255
#define CAMERA_SUBNET_3 255
#define CAMERA_SUBNET_4 240
#define CAMERA_DNS_PRIMARY_1 172
#define CAMERA_DNS_PRIMARY_2 20
#define CAMERA_DNS_PRIMARY_3 10
#define CAMERA_DNS_PRIMARY_4 1
#define CAMERA_DNS_SECONDARY_1 8
#define CAMERA_DNS_SECONDARY_2 8
#define CAMERA_DNS_SECONDARY_3 8
#define CAMERA_DNS_SECONDARY_4 8
